import Navbar from '@/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import IconCarousel from '@/components/slider'
import { FaGithub, FaJava, FaNodeJs, FaPython, FaReact } from 'react-icons/fa'

const inter = Inter({ subsets: ['latin'] })
const defaultIcons = [
  <FaGithub key="github" />,
  <FaJava key="java" />,
  <FaPython key="python" />,
  <FaReact key="react" />,
  <FaNodeJs key="node" />,
];
export const metadata = {
  title: 'Github Wave',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className}`}>
        <IconCarousel />
        <Navbar />
        {children}
      </body>
    </html>
  )
}
